app = "n8n-waha2"

[build]
  dockerfile = "./Dockerfile"

[env]
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  GENERIC_TIMEZONE = "America/Sao_Paulo"
  N8N_LOG_LEVEL = "debug"
  N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE = "true"
  N8N_DIAGNOSTICS_ENABLED = "off"

[http_service]
  internal_port = 5678
  force_https = true

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"
